# Generated by Django 2.1.7 on 2019-03-13 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_name', models.CharField(max_length=10, unique=True)),
                ('rd_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['rd_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['r_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_name', models.CharField(max_length=10, unique=True)),
                ('rd_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['rd_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conv_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_name', models.CharField(max_length=10, unique=True)),
                ('rd_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['rd_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['r_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plug_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prod_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateField()),
                ('p_plant', models.CharField(blank=True, max_length=1)),
                ('p_cancelled', models.BooleanField(default=False)),
                ('p_plan', models.IntegerField(default=10000)),
                ('p_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Apparatus')),
                ('p_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Batch')),
                ('p_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Container')),
                ('p_conveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Conveyor')),
                ('p_marking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Marking')),
            ],
        ),
        migrations.CreateModel(
            name='Supp_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_time_a', models.TimeField(blank=True)),
                ('s_time_p', models.TimeField(blank=True)),
                ('prod_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production')),
            ],
        ),
        migrations.AddField(
            model_name='prod_time',
            name='f_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='prod_time',
            name='f_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plug_time',
            name='f_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='plug_time',
            name='f_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conv_time',
            name='f_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='conv_time',
            name='f_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app_time',
            name='f_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='app_time',
            name='f_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
