# Generated by Django 2.1.7 on 2019-03-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.CharField(max_length=6)),
                ('app_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('marking', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='boil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
                ('plan', models.IntegerField(default=10000)),
                ('time_probe', models.TimeField()),
                ('time_start', models.TimeField()),
                ('b_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apparatus')),
                ('b_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batch')),
            ],
        ),
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_number', models.CharField(max_length=6)),
                ('cont_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='conveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_number', models.CharField(max_length=6)),
                ('conv_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lab_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_time', models.TimeField()),
                ('admission_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batch')),
            ],
        ),
        migrations.AddField(
            model_name='boil',
            name='b_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.container'),
        ),
        migrations.AddField(
            model_name='boil',
            name='b_conveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.conveyor'),
        ),
    ]
