# Generated by Django 2.1.7 on 2019-03-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_adm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_time', models.TimeField()),
                ('lab_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='plug_adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_time', models.TimeField(auto_now_add=True)),
                ('lab_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marking', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('cancelled', models.BooleanField(default=False)),
                ('plan', models.IntegerField(default=10000)),
                ('p_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apparatus')),
                ('p_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.container')),
                ('p_conveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.conveyor')),
            ],
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_apparatus',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_batch',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_container',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_conveyor',
        ),
        migrations.RemoveField(
            model_name='lab_admission',
            name='admission_batch',
        ),
        migrations.DeleteModel(
            name='boil',
        ),
        migrations.DeleteModel(
            name='lab_admission',
        ),
        migrations.AddField(
            model_name='plug_adm',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.production'),
        ),
        migrations.AddField(
            model_name='lab_adm2',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.production'),
        ),
    ]
