# Generated by Django 2.1.7 on 2019-03-12 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20190312_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_test_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField()),
                ('fix_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conv_test_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField()),
                ('fix_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plug_adm_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField()),
                ('fix_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_adm_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField()),
                ('fix_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lab_adm2',
            name='lab_user',
        ),
        migrations.RemoveField(
            model_name='lab_adm2',
            name='prod_row',
        ),
        migrations.RemoveField(
            model_name='plug_adm',
            name='lab_user',
        ),
        migrations.RemoveField(
            model_name='plug_adm',
            name='prod_row',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='marking',
        ),
        migrations.AlterField(
            model_name='apparatus',
            name='app_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='cont_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='conveyor',
            name='conv_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Batch'),
        ),
        migrations.AlterField(
            model_name='production',
            name='marking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Marking'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_apparatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Apparatus'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Container'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_conveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Conveyor'),
        ),
        migrations.DeleteModel(
            name='lab_adm2',
        ),
        migrations.DeleteModel(
            name='plug_adm',
        ),
        migrations.AddField(
            model_name='prod_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='plug_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='conv_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='app_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
    ]
