# Generated by Django 2.1.7 on 2019-03-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_l_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marking', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('cancelled', models.BooleanField(default=False)),
                ('plan', models.IntegerField(default=10000)),
                ('time_probe', models.TimeField()),
                ('time_start', models.TimeField()),
                ('app_test_time', models.TimeField()),
                ('admission_plug_time', models.TimeField()),
                ('conv_probe_time', models.TimeField()),
                ('adm_prod_time', models.TimeField()),
                ('prod_fact_time', models.TimeField()),
                ('p_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apparatus')),
                ('p_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.container')),
                ('p_conveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.conveyor')),
            ],
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_apparatus',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_batch',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_container',
        ),
        migrations.RemoveField(
            model_name='boil',
            name='b_conveyor',
        ),
        migrations.RemoveField(
            model_name='l_admission',
            name='admission_batch',
        ),
        migrations.DeleteModel(
            name='boil',
        ),
    ]
