# Generated by Django 2.1.7 on 2019-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='r_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='marking',
            name='r_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
