# Generated by Django 2.1.7 on 2019-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190301_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_admission',
            name='admission_batch',
        ),
        migrations.AlterField(
            model_name='production',
            name='adm_prod_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='admission_plug_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='app_test_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='conv_probe_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='plan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='prod_fact_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='time_probe',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='time_start',
            field=models.TimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='lab_admission',
        ),
    ]
