# Generated by Django 2.1.7 on 2019-03-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20190312_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparatus2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_d_name', models.CharField(max_length=10, unique=True)),
                ('ref_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['ref_d_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['ref_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_d_name', models.CharField(max_length=10, unique=True)),
                ('ref_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['ref_d_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conveyor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_d_name', models.CharField(max_length=10, unique=True)),
                ('ref_descr', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['ref_d_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fix_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marking2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['ref_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
                ('plan', models.IntegerField(default=10000)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Batch2')),
                ('marking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Marking2')),
                ('p_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Apparatus2')),
                ('p_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Container2')),
                ('p_conveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Conveyor2')),
            ],
        ),
        migrations.AlterField(
            model_name='app_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='conv_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='plug_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='prod_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Batch'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_apparatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Apparatus'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Container'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_conveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Conveyor'),
        ),
        migrations.AlterField(
            model_name='suppose_times',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AddField(
            model_name='fix_time',
            name='fix_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production2'),
        ),
        migrations.AddField(
            model_name='fix_time',
            name='fix_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
