# Generated by Django 2.1.7 on 2019-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190305_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='plan',
            field=models.IntegerField(default=10000),
        ),
    ]
