# Generated by Django 2.1.7 on 2019-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190305_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='time_probe',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
