# Generated by Django 2.1.7 on 2019-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190305_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='adm_prod_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='admission_plug_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='app_test_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='conv_probe_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='prod_fact_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
