# Generated by Django 2.1.7 on 2019-03-12 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20190312_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_test_time2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_time', models.TimeField(auto_now_add=True)),
                ('fix_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production2')),
                ('fix_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='app_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='conv_test_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='plug_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='prod_adm_time',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Batch'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_apparatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Apparatus'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Container'),
        ),
        migrations.AlterField(
            model_name='production',
            name='p_conveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Conveyor'),
        ),
        migrations.AlterField(
            model_name='suppose_times',
            name='prod_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Production'),
        ),
    ]
